<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Nullable>disable</Nullable>
    <PackageRoot>$(MSBuildThisFileDirectory)..\..\.deps\YYGC-grid-business\AnyRuleD~\Packages</PackageRoot>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="$(PackageRoot)/com.tsgame.anyrules/Runtime/Core/**/*.cs" />
    <Compile Include="$(PackageRoot)/com.tsgame.anyrules.networking/Protocol/*.cs" />
  </ItemGroup>
</Project>
