"""Import the supplied v16.1 mask rows verbatim; never overwrite artist assets."""
import hashlib
import json
import re
import shutil
import sys
from pathlib import Path
from PIL import Image

source = Path(sys.argv[1])
root = Path(__file__).resolve().parents[2]
target = root / 'tools/contour-reference'
target.mkdir(exist_ok=True)
html = source.read_text(encoding='utf-8')
rows = json.loads(re.search(r'const BACKGROUND_MASK_ROWS = (.*?);', html).group(1))
packed = bytes(int(row, 2) for variant in rows for mask in variant for row in mask)
asset = root / 'Game/Assets/DarkNights/Res/Art/Custom/CaveContourStatic'
asset.mkdir(exist_ok=True)
image = Image.new('RGBA', (128, 32))
for v in range(4):
    for m in range(16):
        for y in range(8):
            for x in range(8):
                if rows[v][m][y][x] == '1':
                    image.putpixel((v * 32 + m % 4 * 8 + x, m // 4 * 8 + y), (255, 255, 255, 255))
png = asset / 'background-mask-v16.png'
if png.exists():
    raise RuntimeError('Refusing to overwrite existing mask asset')
image.save(png)
shutil.copyfile(source, target / 'source-v16.1.html')
(target / 'mask-rows.json').write_text(json.dumps(rows), encoding='utf-8')
cs = root / 'Game/Assets/DarkNights/Scripts/Core/Logic/Terrain/BackgroundMaskAtlas.cs'
values = ',\n'.join('            ' + ', '.join(str(b) for b in packed[i:i+16]) for i in range(0, len(packed), 16))
cs.write_text('''// Generated by tools/cave-art/import-contour-source.py from the supplied H5; do not hand edit.
namespace DarkNights.Core.Logic.Terrain
{
    /// <summary>H5 v16.1 固定四组掩码的逐行位图；纯只读表现规则，所有变体共享边界采样。</summary>
    public static class BackgroundMaskAtlas
    {
        private static readonly byte[] Rows = new byte[]
        {
''' + values + '''
        };
        public static bool Sample(int variant, int mask, int x, int y) =>
            (Rows[(variant * 16 + mask) * 8 + y] & (128 >> x)) != 0;
    }
}
''', encoding='utf-8')
manifest = {'source': source.name, 'sha256': hashlib.sha256(source.read_bytes()).hexdigest(),
            'maskSha256': hashlib.sha256(packed).hexdigest(), 'nativeTilePixels': 8,
            'atlasPixels': [128, 32], 'method': 'Verbatim H5 4 variants x 16 binary masks; no AI generation or rescaling'}
(asset / 'source.json').write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding='utf-8')
print(json.dumps(manifest))
