<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><LangVersion>9.0</LangVersion><EnableDefaultCompileItems>false</EnableDefaultCompileItems><SourceRoot Condition="'$(SourceRoot)' == ''">../..</SourceRoot></PropertyGroup><ItemGroup><Compile Include="$(SourceRoot)/Game/Assets/DarkNights/Scripts/Core/**/*.cs"/><Compile Include="Probe.cs"/></ItemGroup></Project>